name: Pruebas Unitarias - Usuario Java

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compilar el proyecto
        run: cd monitor-peso && mvn compile

      - name: Ejecutar pruebas unitarias
        run: cd monitor-peso && mvn test
